site_name: Manuale Utente
copyright: Copyright &copy; 2024 - 2025 ALimitedGroup
docs_dir: 03-PB/manuale-utente
site_dir: dist/docs

nav:
  - Introduzione: index.md
  - Installazione:
      - Requisiti:
          - Requisiti Hardware: installazione/requisiti/requisiti-hw.md
          - Requisiti Software: installazione/requisiti/requisiti-sw.md
      - Preparazione del Sistema:
          - Installazione del Software: installazione/preparazione-del-sistema/01-installazione-sw.md
          - Personalizzare la configurazione: installazione/preparazione-del-sistema/02-configurare-ms.md
          - Avviare il Sistema: installazione/preparazione-del-sistema/03-avvio-sistema.md
    # Forse: aggiungere "Installazione con Kubernetes" 👀
  - Operazione:
      - Backup: operazione/backup.md
  - Quickstart: quickstart.md # tutorial, per iniziare in 5 minuti ad usare il software
  - Concetti:
      - Tipi di utenti: concetti/tipi-utenti.md
      - Autenticazione: concetti/autenticazione.md
      - Merce: concetti/merci.md
      - Ordine: concetti/ordini.md
      - Riassortimento: concetti/riassortimenti.md
      - Trasferimento: concetti/trasferimenti.md
  - Guide:
      - Registrare un nuovo utente: guide/registrazione.md
      - Effettuare il login: guide/login.md
      - Aggiungere una merce: guide/aggiunta-merce.md
  - Riferimento API:
      - GET /api/v1/ping: reference/ping.md
      - POST /api/v1/login: reference/login.md
      - GET /api/v1/is_logged: reference/is_logged.md
      - GET /api/v1/goods: reference/get_goods.md
      - GET /api/v1/warehouses: reference/get_warehouses.md
      - GET /api/v1/orders: reference/get_orders.md
      - GET /api/v1/transfers: reference/get_transfers.md
      - POST /api/v1/goods: reference/create_good.md
      - POST /api/v1/orders: reference/create_order.md
      - POST /api/v1/transfers: reference/create_transfer.md
      - PUT /api/v1/goods/:good_id: reference/update_good.md
      - POST /api/v1/goods/:good_id/warehouse/:warehouse_id/stock: reference/add_stock.md
      - DELETE /api/v1/goods/:good_id/warehouse/:warehouse_id/stock: reference/remove_stock.md

hooks:
  - 03-PB/manuale-utente/preprocess.py

theme:
  name: material
  language: it

  features:
    - navigation.instant
    - navigation.tabs
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ALimitedGroup
    - icon: material/web
      link: https://alimitedgroup.github.io
