on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup typst
        uses: typst-community/setup-typst@v3
      - name: Compile Typst files
        run: python3 .github/workflows/compile.py
      - name: Upload website files
        id: upload
        uses: actions/upload-artifact@v4
        with:
          path: ./dist
      - name: Comment on PR
        run: |
          bash .github/workflows/comment-pull.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUM: ${{ github.event.number }}
          LINK: ${{ steps.upload.outputs.artifact-url }}
